name: Kross post sample

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'ready to publish' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEV_TO_API_KEY: ${{secrets.DEV_TO_API_KEY}}
        PRIMARY_SOURCE: 'dev.to' # defaults to dev.to. It can be hashnode or medium
        SECONDARY_SOURCES: '' # Eg: hashnode,medium. Do not include the primary source